### PR TITLE
add screenshots to docs for LiqpayCheckout

### PR DESCRIPTION
**Pull request by gianpaj**
BTW thanks for making this awesome RN module! 🎉

### CODE REVIEW

**Comment by vasilich6107** [comment]
Thanks for PR

**Comment by gianpaj** [comment]
LOL, I realised last night what these "native" SDKs really do is just open a Webview...

I don't understand why they created the SDKs and not just write instructions on how to open a Webview and get a callback if the payment was successful or not

**Comment by vasilich6107** [comment]
Good point)
But we can assume that native SDK serves like a wrapper with consistent interface. So they can change inner implementation without much pain for consumers.

**Comment by vasilich6107** [comment]
In addition you can see that current SDKs documentation is awful. We can imagine how bad it can be if there will be more than several methods to call :-)

**Comment by gianpaj** [comment]
You're right. Though I manage to generate the base64 string with 10 lines of JS code instead of installing Java and iOS modules, etc.

It's not like the callbacks (at least in JS) provide any good information

**Pull request merged**
